name: Poplar
favicon: null
layout_spectrum: 0.6967170278076082
typography_spectrum: 0.04254110436886549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9398807869292796
  lightness: 0.054779599187895656
  saturation: 0.9249109372030944
  rhythmicContrast: 0.8942846930585802
purpose: []
